### ISSUE TITLE
404 GET /bower_components/angular-loading-bar/src/loading-bar.js 404 5.070 ms - 1580

### ISSUE THREAD

**Issue by rogerfanrui** [hyperchaincn/Digital-Wallet#1]
## 操作顺序如下:
- 安装nodejs 
- 安装bower (cnpm install -g bower)
- 安装mongodb

进入目录后运行 npm start ,访问localhost:3000,报错如下:
```
GET /bower_components/angular-loading-bar/src/loading-bar.js 404 5.070 ms - 1580
Error: Not Found
    at /opt/Digital-Wallet/app.js:46:13
    at Layer.handle [as handle_request] (/opt/Digital-Wallet/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/opt/Digital-Wallet/node_modules/express/lib/router/index.js:312:13)
    at /opt/Digital-Wallet/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/opt/Digital-Wallet/node_modules/express/lib/router/index.js:330:12)
    at next (/opt/Digital-Wallet/node_modules/express/lib/router/index.js:271:10)
    at /opt/Digital-Wallet/node_modules/express/lib/router/index.js:618:15
    at next (/opt/Digital-Wallet/node_modules/express/lib/router/index.js:256:14)
    at Function.handle (/opt/Digital-Wallet/node_modules/express/lib/router/index.js:176:3)
    at router (/opt/Digital-Wallet/node_modules/express/lib/router/index.js:46:12)
    at Layer.handle [as handle_request] (/opt/Digital-Wallet/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/opt/Digital-Wallet/node_modules/express/lib/router/index.js:312:13)
    at /opt/Digital-Wallet/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/opt/Digital-Wallet/node_modules/express/lib/router/index.js:330:12)
    at next (/opt/Digital-Wallet/node_modules/express/lib/router/index.js:271:10)
    at /opt/Digital-Wallet/node_modules/express/lib/router/index.js:618:15

```

因对Nodejs不是很熟悉 麻烦解答

**Comment by cspilgrimzww** [comment]
文档此处遗漏了一步，安装bower之后需要再执行一下bower install

**Comment by rogerfanrui** [comment]
嗯 我搜了一下 也运行过了,新的错误如下:
```
GET /bower_components/bootstrap/dist/css/bootstrap.min.css 404 21.882 ms - 1580
GET /bower_components/ng-img-crop/compile/minified/ng-img-crop.css 404 21.666 ms - 1580
GET /bower_components/angular-loading-bar/src/loading-bar.css 404 21.469 ms - 1580
GET /bower_components/font-awesome-animation/dist/font-awesome-animation.min.css 404 19.952 ms - 1580
GET /css/font-awesome.min.css 304 23.172 ms - -
Error: Not Found
    at /opt/Digital-Wallet/app.js:46:13
    at Layer.handle [as handle_request] (/opt/Digital-Wallet/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/opt/Digital-Wallet/node_modules/express/lib/router/index.js:312:13)
    at /opt/Digital-Wallet/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/opt/Digital-Wallet/node_modules/express/lib/router/index.js:330:12)
    at next (/opt/Digital-Wallet/node_modules/express/lib/router/index.js:271:10)
    at /opt/Digital-Wallet/node_modules/express/lib/router/index.js:618:15
    at next (/opt/Digital-Wallet/node_modules/express/lib/router/index.js:256:14)
    at Function.handle (/opt/Digital-Wallet/node_modules/express/lib/router/index.js:176:3)
    at router (/opt/Digital-Wallet/node_modules/express/lib/router/index.js:46:12)
    at Layer.handle [as handle_request] (/opt/Digital-Wallet/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/opt/Digital-Wallet/node_modules/express/lib/router/index.js:312:13)
    at /opt/Digital-Wallet/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/opt/Digital-Wallet/node_modules/express/lib/router/index.js:330:12)
    at next (/opt/Digital-Wallet/node_modules/express/lib/router/index.js:271:10)
    at /opt/Digital-Wallet/node_modules/express/lib/router/index.js:618:15
Error: Not Found
```
执行完成之后目录结构如下:
![](http://ww1.sinaimg.cn/large/6262c3a5gy1fm1dw23b52j208y0f1glu.jpg)

**Comment by rogerfanrui** [comment]
找到问题了,是执行bower install失败. 
```
bower angular-base64#^2.0.5             ECMDERR Failed to execute "git ls-remote --tags --heads https://github.com/ninjatronic/angular-base64.git", exit code of #128 fatal: unable to access 'https://github.com/ninjatronic/angular-base64.git/': Empty reply from server

Additional error details:
fatal: unable to access 'https://github.com/ninjatronic/angular-base64.git/': Empty reply from server
```
一般这种问题怎么处理呢

**Comment by rogerfanrui** [comment]
源代码加上这一行:
> app.use("/bower_components",express.static(__dirname+'/bower_components'));
